"""
Execution engine for the sieveon Memory Control Plane
Executes the plans generated by the planner using various retrieval strategies
"""

import asyncio
import contextvars
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from ..extraction.entropy_gate import escape_surrealql, fts_keywords, sanitize_fts_query
from ..mcp.core import _clean_output, _extract_result, _query_surreal
from ..router.cost_awareness import cost_tracker
from ..router.budget import BudgetLevel, BudgetTracker


class BudgetExceeded(Exception):
    """Raised when a strategy tries to exceed its allocated DB budget."""


RRF_K = 60
MAX_EXPANSION_QUERIES = 5
PPR_DAMPING = 0.5
PPR_ITERS = 50
PPR_MAX_NODES = 300


def personalized_pagerank(
    adjacency: Dict[str, Dict[str, float]],
    seeds: Dict[str, float],
    damping: float = PPR_DAMPING,
    iters: int = PPR_ITERS,
) -> Dict[str, float]:
    """Personalized PageRank over an undirected weighted graph (pure function).

    adjacency: node -> {neighbor: weight}. Seeds get the personalization mass
    (IDF-penalized upstream: weight / (1 + degree) so hub nodes don't dominate
    the diffusion -- HippoRAG-style). No numpy needed: power iteration over
    dicts is plenty fast below PPR_MAX_NODES.
    """
    nodes = [n for n in adjacency if adjacency[n]] or list(adjacency)
    if not nodes:
        return {}
    total_seed = sum(max(0.0, seeds.get(n, 0.0)) for n in nodes) or 1.0
    rank = {n: max(0.0, seeds.get(n, 0.0)) / total_seed for n in nodes}
    # Column-stochastic transition (undirected: normalize by neighbor degree mass)
    out_mass = {}
    for n in nodes:
        out_mass[n] = sum(max(0.0, w) for w in adjacency[n].values()) or 1.0
    for _ in range(max(1, iters)):
        new_rank: Dict[str, float] = {}
        for n in nodes:
            inflow = 0.0
            for m in nodes:
                w = adjacency[m].get(n, 0.0)
                if w > 0:
                    inflow += rank[m] * (w / out_mass[m])
            teleport = max(0.0, seeds.get(n, 0.0)) / total_seed
            new_rank[n] = damping * inflow + (1.0 - damping) * teleport
        rank = new_rank
    return rank


_COORD_SPLIT_RE = re.compile(r"\s+and\s+", re.IGNORECASE)


def split_multihop_query(query: str) -> List[str]:
    """Split a coordinated multi-hop query into sub-queries (no LLM).

    "Who founded Acme and where is it based" -> ["Who founded Acme",
    "where is it based"]. Entity carryover is implicit: each part is searched
    independently and fused via RRF downstream. Returns [query] when no
    coordination is found or parts are too short to stand alone.
    """
    parts = [p.strip(" ,.!?;:") for p in _COORD_SPLIT_RE.split(query or "")]
    parts = [p for p in parts if len(p.split()) >= 2]
    if len(parts) < 2:
        return [query]
    return parts

# A logically invalidated fact is only current while its validity window is open.
# Every read path in tools.py / core.py already applies this filter; the retrieval
# strategies did not, so a superseded value was still served as a current fact and
# memory_update's contract was void for 7 of the 8 strategies.
ACTIVE_FACT_FILTER = "(valid_until IS NONE OR valid_until > time::now())"


def _parse_ts(value: Any) -> Optional[datetime]:
    """Parse a SurrealDB datetime into an aware datetime, or None if unparsable."""
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=timezone.utc)
    if not isinstance(value, str):
        return None
    text = value.strip().replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)


class RetrievalStrategy(Enum):
    """Available retrieval strategies"""

    EVENT_LOG_FIRST = "event_log_first"
    KNOWLEDGE_GRAPH_FIRST = "knowledge_graph_first"
    HYBRID_WITH_GRAPH_EXPANSION = "hybrid_with_graph_expansion"
    COMPOSITE_KG_VECTOR = "composite_kg_vector"
    KNOWLEDGE_GRAPH_WITH_INVALIDATION = "knowledge_graph_with_invalidation"
    HYBRID_BM25_VECTOR_TEMPORAL = "hybrid_bm25_vector_temporal"
    HYBRID_FALLBACK = "hybrid_fallback"
    SEMANTIC_HYBRID = "semantic_hybrid"
    GRAPH_PPR_RERANK = "graph_ppr_rerank"
    DECOMPOSED_MULTIHOP = "decomposed_multihop"


def _channel_diagnostics(
    lexical: Optional[List[Dict]],
    vector: Optional[List[Dict]],
) -> Dict[str, Any]:
    """Per-channel retrieval diagnostics, kept separate on purpose.

    Ranking wants a single fused ordering. Confidence does not: it wants to
    know how strong the evidence was before the channels were mixed. Once
    fused, that information is gone -- a top hit that only the vector channel
    likes looks identical to one both channels agree on.

    These four numbers are the Query Performance Prediction diagnostics from
    the IR literature (top vector score, lexical hit count, top BM25, and
    cross-channel agreement). They are inputs to a calibrated accept
    decision, not a score to rank by.
    """
    lexical = lexical or []
    vector = vector or []

    bm25_values = [
        float(i.get("bm25") or 0) for i in lexical if i.get("bm25") is not None
    ]
    vec_values = [
        float(i.get("vec_score") or 0) for i in vector if i.get("vec_score") is not None
    ]

    top_lexical = lexical[0].get("id") if lexical else None
    top_vector = vector[0].get("id") if vector else None

    return {
        "top_vec_score": max(vec_values) if vec_values else 0.0,
        "lexical_hits": len(lexical),
        "max_bm25": max(bm25_values) if bm25_values else 0.0,
        "channels_agree": bool(
            top_lexical is not None and top_lexical == top_vector
        ),
    }


class RetrievalExecutor:
    """Executes retrieval operations using different strategies"""

    def __init__(self):
        # ContextVar instead of a plain attribute: concurrent tasks sharing one
        # executor must not see each other's budget tracker.
        self._budget: contextvars.ContextVar = contextvars.ContextVar(
            "sieveon_budget_tracker", default=None
        )

    def _charge_db(self, count: int = 1):
        """Charge DB calls against the active budget and enforce the limit."""
        budget = self._budget.get()
        if budget is None:
            return
        if budget.is_over_budget():
            raise BudgetExceeded("Over budget")
        budget.increment_db_calls(count)

    async def _gather_bounded(self, coros: List[Any]) -> List[Any]:
        """Run searches concurrently, tolerating budget exhaustion.

        A BudgetExceeded inside asyncio.gather() cancels the sibling tasks and
        propagates, which turned "ran out of budget mid-expansion" into a total
        query failure. Expansion is an optional enrichment step, so a partial
        result set is the correct outcome: the cheapest searches (which are
        ordered first) survive and the rest come back as None.
        """
        if not coros:
            return []

        async def _guarded(coro):
            try:
                return await coro
            except BudgetExceeded:
                return None

        return await asyncio.gather(*(_guarded(c) for c in coros))

    @staticmethod
    def _rrf_fuse(*ranked_lists: List[Dict]) -> List[Dict]:
        """Reciprocal Rank Fusion over one or more ranked result lists."""
        seen_ids = set()
        fused: List[Dict] = []
        offset = 0
        for ranked in ranked_lists:
            for rank, item in enumerate(ranked):
                item_id = item.get("id")
                if not item_id or item_id in seen_ids:
                    continue
                seen_ids.add(item_id)
                item["_rrf_score"] = 1.0 / (RRF_K + offset + rank)
                fused.append(item)
            offset += len(ranked)

        fused.sort(key=lambda x: x.get("_rrf_score", 0.0), reverse=True)
        for item in fused:
            item["relevance_score"] = round(item.pop("_rrf_score", 0.0), 4)
        return fused

    async def execute_strategy(
        self,
        strategy: RetrievalStrategy,
        query: str,
        budget_tracker: BudgetTracker,
        **kwargs,
    ) -> Dict[str, Any]:
        """
        Execute a retrieval strategy with budget enforcement and cost tracking.

        query_type (optional kwarg, e.g. "factual"): the classified query type.
        Recorded alongside the outcome so the router learns per context, not
        globally. Absent callers record under "unknown" (legacy behaviour).
        """
        start_time = time.time()
        success = True
        relevance_score = 0.5
        budget_token = self._budget.set(budget_tracker)
        start_db_calls = budget_tracker.db_calls
        # Consumed here for cost tracking; must not leak into the strategy
        # implementations below (they receive **kwargs).
        query_type = kwargs.pop("query_type", None)

        try:
            if budget_tracker.is_over_budget():
                raise BudgetExceeded("Over budget")

            if strategy == RetrievalStrategy.EVENT_LOG_FIRST:
                result = await self._execute_event_log_first(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.KNOWLEDGE_GRAPH_FIRST:
                result = await self._execute_knowledge_graph_first(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.HYBRID_WITH_GRAPH_EXPANSION:
                result = await self._execute_hybrid_with_graph_expansion(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.COMPOSITE_KG_VECTOR:
                result = await self._execute_composite_kg_vector(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.KNOWLEDGE_GRAPH_WITH_INVALIDATION:
                result = await self._execute_knowledge_graph_with_invalidation(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.HYBRID_BM25_VECTOR_TEMPORAL:
                result = await self._execute_hybrid_bm25_vector_temporal(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.HYBRID_FALLBACK:
                result = await self._execute_hybrid_fallback(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.SEMANTIC_HYBRID:
                result = await self._execute_semantic_hybrid(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.GRAPH_PPR_RERANK:
                result = await self._execute_graph_ppr_rerank(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.DECOMPOSED_MULTIHOP:
                result = await self._execute_decomposed_multihop(
                    query, budget_tracker, **kwargs
                )
            else:
                raise ValueError(f"Unknown strategy: {strategy}")

            relevance_score = self._calculate_relevance_score(result, query)

        except Exception as e:
            success = False
            logging.error("Strategy %s failed: %s", strategy.value, e, exc_info=True)
            result = {
                "error": str(e),
                "error_type": type(e).__name__,
                "success": False,
                "strategy": strategy.value,
                "events": [],
                "entities": [],
                "facts": [],
                "query": query,
            }
        finally:
            self._budget.reset(budget_token)
            latency = time.time() - start_time
            num_queries = budget_tracker.db_calls - start_db_calls

            cost_tracker.record_request(
                strategy=strategy.value,
                latency=latency,
                success=success,
                num_queries=num_queries,
                relevance=relevance_score,
                query_type=query_type,
            )

            # Persist learned costs periodically (every 25 requests). Best
            # effort and detached: a failed snapshot only loses recent
            # learning, and it must never block or break retrieval.
            try:
                if cost_tracker.total_records() % 25 == 0:
                    from src.mcp.core import save_router_costs

                    async def _snapshot():
                        try:
                            await save_router_costs()
                        except Exception:
                            logging.warning(
                                "Router cost snapshot failed; learned costs "
                                "since the last one are lost", exc_info=True)

                    task = asyncio.create_task(_snapshot())
                    task.add_done_callback(lambda t: t.exception() if not t.cancelled() else None)
            except Exception:
                # Never break retrieval over a bookkeeping failure, but do not
                # hide it either -- a permanently broken snapshot is invisible
                # otherwise.
                logging.warning("Router cost snapshot could not be scheduled",
                                exc_info=True)

        # Surfaced so callers can see the score that was fed into the router's
        # cost tracking instead of having to reconstruct it.
        result["relevance_score"] = relevance_score

        return result

    _TERM_RE = re.compile(r"\w{3,}")

    # Stopwords for coverage: question words, auxiliaries, articles and glue.
    # Without these, "Who is where and what?" matches any sentence containing
    # "who/the/and" and scores as high as a real answer. Content terms only.
    _STOPWORDS = frozenset({
        "who", "what", "which", "where", "when", "why", "how",
        "is", "are", "was", "were", "be", "been", "being",
        "do", "does", "did", "have", "has", "had", "having",
        "the", "a", "an", "and", "or", "of", "to", "in", "on",
        "for", "with", "by", "from", "at", "as", "it", "its",
        "this", "that", "these", "those",
        "i", "you", "he", "she", "we", "they", "them", "his", "her",
        "not", "no", "yes", "if", "then", "than", "so", "such",
        "only", "also", "just", "about", "into", "over", "after",
        "before", "between", "through", "during", "there", "here",
    })

    @classmethod
    def _content_terms(cls, text: str) -> set:
        """Terms that carry meaning: length >= 3 and not a stopword."""
        return {t for t in cls._TERM_RE.findall((text or "").lower())
                if t not in cls._STOPWORDS}

    @classmethod
    def _item_text(cls, item: Dict[str, Any]) -> str:
        """Flatten the searchable text of a result item (event/entity/fact)."""
        parts: List[Any] = [
            item.get("content"),
            item.get("name"),
            item.get("predicate"),
            item.get("in_name"),
            item.get("out_name"),
        ]
        for edge in ("in", "out"):
            value = item.get(edge)
            if isinstance(value, dict):
                parts.append(value.get("name"))
                parts.append(value.get("type"))
            elif isinstance(value, str):
                parts.append(value)
        return " ".join(str(p) for p in parts if p).lower()

    @classmethod
    def _calculate_relevance_score(cls, result: Dict[str, Any], query: str) -> float:
        """Estimate how likely this result is to actually answer the query.

        This is an accept/abstain number, not a ranking score. Ranking is done
        by the strategies (rank-based fusion); this answers a different
        question -- is there anything here worth answering with.

        The previous version averaged the top three vector scores and mixed in
        a term-coverage ratio. Measured on the retrieval gold set that scored
        a paraphrase 0.36 and an unrelated query 0.31, i.e. no separation at
        all, because averaging three scores and adding coverage dilutes
        precisely the signal that discriminates. The top-1 score separates
        cleanly: answerable queries 0.524-0.818, no-answer probes 0.224-0.335,
        AUC 1.000 on that set.

        Two caveats, both load-bearing:

        * A cosine score is not comparable across queries in general -- a
          ranking-trained embedding optimises relative order within a query,
          not an absolute probability. The value below is therefore
          calibrated empirically for this embedding model and corpus, not a
          universal constant. Re-measure with scripts/eval_retrieval.py after
          changing the embedding model; expect to move.
        * The gold set is 30 answerable and 4 no-answer queries. Four
          negatives is too few to pin the operating point precisely, so the
          threshold sits in the middle of the observed gap rather than on a
          measured optimum.

        Lexical corroboration enters only as a bonus on top of the vector
        signal, not as a weighted average: raw BM25 is unbounded and cosine is
        bounded, so mixing them directly is not sound, and the earlier 0.5/0.5
        blend was in fact ~98% vector score because the RRF term is two orders
        of magnitude smaller.
        """
        if "error" in result:
            return 0.1

        items: List[Dict] = []
        for key in ("events", "entities", "facts"):
            value = result.get(key, [])
            if isinstance(value, list):
                items.extend(i for i in value if isinstance(i, dict))

        if not items:
            return 0.2

        diag = result.get("retrieval_diagnostics") or {}

        # Top-1, not a mean over the top three.
        top_vec = diag.get("top_vec_score")
        if not isinstance(top_vec, (int, float)):
            vec_scores = [
                float(i["vec_score"]) for i in items
                if isinstance(i.get("vec_score"), (int, float))
            ]
            top_vec = max(vec_scores) if vec_scores else 0.0

        if top_vec <= 0.0:
            # No vector channel (lexical-only or graph-only strategies). Fall
            # back to whether the lexical channel found anything, which on the
            # gold set separates at AUC 0.992.
            hits = diag.get("lexical_hits")
            if isinstance(hits, int):
                return round(min(1.0, 0.3 + 0.1 * min(hits, 7)), 4)
            return 0.3

        score = top_vec
        # Corroboration only ever raises the estimate. Cross-channel agreement
        # is a genuine signal (AUC 0.933 on the gold set) but a weaker one
        # than the vector score, so it must not be able to push a query with
        # no semantic match over the accept threshold.
        if diag.get("channels_agree"):
            score += 0.1
        bm25 = diag.get("max_bm25")
        if isinstance(bm25, (int, float)) and bm25 > 0:
            score += 0.05

        return round(max(0.0, min(1.0, score)), 4)


    @staticmethod
    def _temporal_clause(since: Optional[str] = None, until: Optional[str] = None) -> str:
        """SQL fragment restricting event timestamps (B1 temporal path).

        Uses fn::events_at semantics inline so the FTX/vector channels stay
        index-friendly. Values are SurrealQL-escaped ISO datetimes.
        """
        clauses = []
        if since:
            clauses.append(f'AND timestamp >= type::datetime("{escape_surrealql(since)}")')
        if until:
            clauses.append(f'AND timestamp <= type::datetime("{escape_surrealql(until)}")')
        return "\n          ".join(clauses)

    @staticmethod
    def _validity_at_clause(at_time: Optional[str] = None) -> str:
        """Validity window at a fixed point in time (B1: 'was wusste der Agent zu T').

        None -> current validity (valid_until IS NONE OR > now()).
        Set -> valid_from <= T AND (valid_until NONE OR > T), same rule as
        fn::facts_at_time($time) in docs/helper_functions.surql.
        """
        if not at_time:
            return f"AND {ACTIVE_FACT_FILTER}"
        t = escape_surrealql(at_time)
        return f'AND valid_from <= type::datetime("{t}") AND (valid_until IS NONE OR valid_until > type::datetime("{t}"))'

    async def _search_events_ftx(
        self,
        query: str,
        limit: int = 10,
        since: Optional[str] = None,
        until: Optional[str] = None,
    ) -> List[Dict]:
        """Lexical search via FTX index."""
        self._charge_db()
        # Keywords, not the raw question: @@ is strict AND over analyzed terms
        # (verified 2026-09-30 live), so a single rare term empties the result
        # set. @OR@ + BM25 ranking keeps recall: measured on LoCoMo-light
        # (20 questions) evidence-hit 9/20 (AND) vs 18/20 (OR + BM25 top-5).
        # search::score(0) requires BM25 on the index and must be aliased --
        # SurrealDB 3 rejects function calls directly in ORDER BY.
        query_escaped = escape_surrealql(fts_keywords(query))
        forgotten_filter = "forgotten = false"
        temporal = self._temporal_clause(since, until)
        sql = f"""
        SELECT id, content, timestamp, source, metadata, search::score(0) AS bm25
        FROM event
        WHERE content @OR@ '{query_escaped}'
          AND {forgotten_filter}
          {temporal}
        ORDER BY bm25 DESC
        LIMIT {limit * 4};
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_events_vector(
        self,
        query: str,
        limit: int = 10,
        since: Optional[str] = None,
        until: Optional[str] = None,
    ) -> List[Dict]:
        """Semantic search via vector similarity."""
        from src.mcp.core import _embed_query

        query_vector = await _embed_query(query)
        if not query_vector:
            return []
        self._charge_db()
        query_vector_str = "[" + ", ".join(map(str, query_vector)) + "]"
        forgotten_filter = "forgotten = false"
        temporal = self._temporal_clause(since, until)
        sql = f"""
        SELECT id, content, timestamp, source, metadata,
               vector::similarity::cosine(embedding, {query_vector_str}) AS vec_score
        FROM event
        WHERE embedding IS NOT NONE
          AND {forgotten_filter}
          {temporal}
          AND array::len(embedding) = {len(query_vector)}
        ORDER BY vec_score DESC
        LIMIT {limit * 4};
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_recent_events(
        self,
        limit: int = 10,
        since: Optional[str] = None,
        until: Optional[str] = None,
    ) -> List[Dict]:
        """Recency channel: the most recent events, regardless of the query.

        Deliberately not query-conditioned. It is fused with the lexical results
        via RRF to bias towards fresh events; adding a query filter here would
        only turn it into a subset of the FTX results and double-count them.
        since/until bound the window (B1: fn::events_at semantics).
        """
        self._charge_db()
        forgotten_filter = "forgotten = false"
        temporal = self._temporal_clause(since, until)
        sql = f"""
        SELECT id, content, timestamp, source, metadata
        FROM event
        WHERE {forgotten_filter}
          {temporal}
        ORDER BY timestamp DESC
        LIMIT {limit};
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    @staticmethod
    def _validity_clause(include_invalidated: bool) -> str:
        """SQL clause restricting facts to an open validity window."""
        return "" if include_invalidated else f"AND {ACTIVE_FACT_FILTER}"

    async def _search_kg_by_subject(
        self,
        subject: str,
        include_invalidated: bool = False,
        at_time: Optional[str] = None,
    ) -> List[Dict]:
        """Search knowledge graph by subject name.

        Only currently valid facts unless include_invalidated is set; that flag
        exists for the strategy that reports the validity split explicitly.
        at_time pins the validity window (B1, fn::facts_at_time semantics).
        """
        self._charge_db()
        subject_escaped = escape_surrealql(subject)
        validity = (
            ""
            if include_invalidated and not at_time
            else self._validity_at_clause(at_time)
        )
        sql = f"""
        SELECT id,
               in.name AS in_name, in.type AS in_type, in.id AS in_id,
               out.name AS out_name, out.type AS out_type, out.id AS out_id,
               predicate, confidence, valid_from, valid_until
        FROM fact
        WHERE in.name = '{subject_escaped}'
          {validity}
        ORDER BY confidence DESC
        LIMIT 50;
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_kg_by_text(
        self,
        text: str,
        include_invalidated: bool = False,
        at_time: Optional[str] = None,
    ) -> List[Dict]:
        """Search knowledge graph by matching predicate or entity names.

        The OR group is parenthesised so the validity filter applies to all three
        branches instead of binding to the last one only.
        """
        self._charge_db()
        text_escaped = escape_surrealql(fts_keywords(text))
        validity = (
            ""
            if include_invalidated and not at_time
            else self._validity_at_clause(at_time)
        )
        sql = f"""
        SELECT id,
               in.name AS in_name, in.type AS in_type, in.id AS in_id,
               out.name AS out_name, out.type AS out_type, out.id AS out_id,
               predicate, confidence, valid_from, valid_until
        FROM fact
        WHERE (predicate @@ '{text_escaped}'
            OR in.name CONTAINS '{text_escaped}'
            OR out.name CONTAINS '{text_escaped}')
          {validity}
        ORDER BY confidence DESC
        LIMIT 50;
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_entities_by_name(self, name: str) -> List[Dict]:
        """Search entities by name (fulltext via FTX index)."""
        self._charge_db()
        name_escaped = escape_surrealql(fts_keywords(name))
        sql = f"""
        SELECT id, name, type, search::score(0) AS bm25
        FROM entity
        WHERE name @OR@ '{name_escaped}'
        ORDER BY bm25 DESC
        LIMIT 20;
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _expand_graph_bfs(
        self,
        seed_names: List[str],
        at_time: Optional[str] = None,
        max_depth: int = 2,
        per_level: int = MAX_EXPANSION_QUERIES,
    ) -> List[Dict]:
        """Bounded BFS graph expansion (B2).

        Level 0 = seed entity names. Each level queries _search_kg_by_subject
        for up to `per_level` names, collects neighbour names for the next
        level. Budget-exhaustion returns partial results via _gather_bounded.
        Respects at_time validity windows.
        """
        seen_fact_ids: set = set()
        expanded: List[Dict] = []
        frontier = [n for n in dict.fromkeys(seed_names) if n][:per_level]
        seen_names = set(frontier)
        for _ in range(max(1, max_depth)):
            if not frontier:
                break
            level_results = await self._gather_bounded(
                [self._search_kg_by_subject(n, at_time=at_time) for n in frontier[:per_level]]
            )
            next_frontier: List[str] = []
            for more_facts in level_results:
                for f in more_facts or []:
                    fid = f.get("id")
                    if fid and fid not in seen_fact_ids:
                        seen_fact_ids.add(fid)
                        expanded.append(f)
                    for key in ("in_name", "out_name"):
                        neighbour = f.get(key)
                        if neighbour and neighbour not in seen_names:
                            seen_names.add(neighbour)
                            next_frontier.append(neighbour)
            frontier = next_frontier[:per_level]
        return expanded

    async def _execute_event_log_first(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute event log first strategy — search events via FTX + temporal."""
        budget_tracker.increment_tokens(len(query) // 4)
        since = kwargs.get("since")
        until = kwargs.get("until")

        ftx_events, temporal_events = await self._gather_bounded(
            [
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_recent_events(5, since=since, until=until),
            ]
        )
        ftx_events = ftx_events or []
        temporal_events = temporal_events or []

        fused = self._rrf_fuse(ftx_events, temporal_events)[:10]

        return {
            "strategy": "event_log_first",
            "events": _clean_output(fused[:10]),
            "entities": [],
            "facts": [],
            "query": query,
            # Without diagnostics the relevance scorer falls back to 0.3 for
            # this lexical-only strategy, which sits below the summary accept
            # gate -- every event_log_first query then verdicts nothing_found
            # even with a perfect BM25 hit. Report the lexical channel state.
            "retrieval_diagnostics": _channel_diagnostics(ftx_events, []),
        }

    async def _execute_knowledge_graph_first(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute knowledge graph first strategy — search KG + entities."""
        budget_tracker.increment_tokens(len(query) // 4)
        at_time = kwargs.get("at_time")

        # Extract potential subject words from query (simple heuristic)
        words = query.split()
        subjects_to_try = []
        for w in words:
            w_clean = w.strip(",.!?;:")
            if w_clean and w_clean[0].isupper():
                subjects_to_try.append(w_clean)
        if not subjects_to_try:
            subjects_to_try = [query]

        # Search entities and KG in parallel
        searches = [self._search_entities_by_name(s) for s in subjects_to_try[:3]]
        searches.append(self._search_kg_by_text(query, at_time=at_time))

        all_results = await self._gather_bounded(searches)

        entities = []
        seen_entity_ids = set()
        for r in all_results[: len(searches) - 1]:
            for e in r or []:
                eid = e.get("id")
                if eid and eid not in seen_entity_ids:
                    seen_entity_ids.add(eid)
                    entities.append(e)

        facts = []
        seen_fact_ids = set()
        for r in all_results[len(searches) - 1 :]:
            for f in r or []:
                fid = f.get("id")
                if fid and fid not in seen_fact_ids:
                    seen_fact_ids.add(fid)
                    facts.append(f)

        return {
            "strategy": "knowledge_graph_first",
            "events": [],
            "entities": _clean_output(entities),
            "facts": _clean_output(facts),
            "query": query,
            # Fact/entity volume as the lexical-hit proxy so the relevance
            # scorer does not fall back to 0.3 and veto a good KG answer.
            "retrieval_diagnostics": _channel_diagnostics(
                [{"id": f.get("id"), "bm25": f.get("confidence")} for f in facts],
                [],
            ),
        }

    async def _execute_hybrid_with_graph_expansion(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute hybrid with graph expansion — events + KG + BFS entity expansion."""
        budget_tracker.increment_tokens(len(query) // 3)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        ftx_events, kg_facts, entities = await self._gather_bounded(
            [
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_kg_by_text(query, at_time=at_time),
                self._search_entities_by_name(query),
            ]
        )
        ftx_events = ftx_events or []
        kg_facts = kg_facts or []
        entities = entities or []

        # Expand via bounded BFS (B2): seeds -> neighbours -> neighbours-of-neighbours
        expanded_facts = list(kg_facts)
        seen_fact_ids = {f.get("id") for f in kg_facts if f.get("id")}
        subject_names = []
        for ent in entities[:MAX_EXPANSION_QUERIES]:
            ent_name = ent.get("name", "")
            if ent_name and ent_name not in subject_names:
                subject_names.append(ent_name)

        if subject_names:
            bfs_facts = await self._expand_graph_bfs(
                subject_names, at_time=at_time, max_depth=2
            )
            for f in bfs_facts:
                fid = f.get("id")
                if fid and fid not in seen_fact_ids:
                    seen_fact_ids.add(fid)
                    expanded_facts.append(f)

        return {
            "strategy": "hybrid_with_graph_expansion",
            "events": _clean_output(ftx_events),
            "entities": _clean_output(entities),
            "facts": _clean_output(expanded_facts),
            "query": query,
            "retrieval_diagnostics": _channel_diagnostics(ftx_events, []),
        }

    async def _execute_composite_kg_vector(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute composite KG-vector strategy — KG facts + lexical and vector search on events."""
        budget_tracker.increment_tokens(len(query) // 3)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        kg_facts, entities, ftx_events, vec_events = await self._gather_bounded(
            [
                self._search_kg_by_text(query, at_time=at_time),
                self._search_entities_by_name(query),
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_events_vector(query, 10, since=since, until=until),
            ]
        )
        kg_facts = kg_facts or []
        entities = entities or []
        fused = self._rrf_fuse(ftx_events or [], vec_events or [])[:10]

        return {
            "strategy": "composite_kg_vector",
            "events": _clean_output(fused),
            "entities": _clean_output(entities),
            "facts": _clean_output(kg_facts),
            "query": query,
            "retrieval_diagnostics": _channel_diagnostics(ftx_events or [], vec_events or []),
        }

    async def _execute_knowledge_graph_with_invalidation(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute knowledge graph with invalidation — search KG + check for stale facts.

        This is the one strategy that needs the invalidated rows: it reports the
        validity split (active / stale / expired) instead of dropping them.
        """
        budget_tracker.increment_tokens(len(query) // 4)

        kg_facts, entities = await self._gather_bounded(
            [
                self._search_kg_by_text(
                    query,
                    include_invalidated=True,
                    at_time=kwargs.get("at_time"),
                ),
                self._search_entities_by_name(query),
            ]
        )
        kg_facts = kg_facts or []
        entities = entities or []

        # Read-side invalidation only: no writes, facts are split by validity window.
        #
        # "Current" follows ACTIVE_FACT_FILTER, so a fact with a scheduled future end
        # date is still current — the same rule every other read path in the codebase
        # applies. Buckets:
        #   facts         valid_until empty or in the future  -> currently true
        #   expired_facts valid_until in the past            -> superseded
        #   stale_facts   valid_until present but unparsable -> data quality, cannot
        #                 be placed in time; kept in the current set so it is not
        #                 silently dropped, and counted below so it can be alerted on
        now = datetime.now(timezone.utc)
        active_facts = []
        stale_facts = []
        expired_facts = []
        unparsable = 0
        for fact in kg_facts:
            valid_until = fact.get("valid_until")
            if not valid_until:
                active_facts.append(fact)
                continue

            deadline = _parse_ts(valid_until)
            if deadline is None:
                unparsable += 1
                stale_facts.append(fact)
                active_facts.append(fact)
            elif deadline <= now:
                expired_facts.append(fact)
            else:
                active_facts.append(fact)

        if unparsable:
            logging.warning(
                "%d fact(s) carry an unparsable valid_until and could not be placed "
                "in a validity window",
                unparsable,
            )

        return {
            "strategy": "knowledge_graph_with_invalidation",
            "events": [],
            "entities": _clean_output(entities),
            "facts": _clean_output(active_facts),
            "stale_facts": _clean_output(stale_facts),
            "expired_facts": _clean_output(expired_facts),
            "unparsable_valid_until": unparsable,
            "query": query,
        }

    async def _execute_hybrid_bm25_vector_temporal(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute hybrid BM25-vector-temporal — full event search + KG."""
        budget_tracker.increment_tokens(len(query) // 3)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        ftx_events, temporal_events, kg_facts, entities = await self._gather_bounded(
            [
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_recent_events(5, since=since, until=until),
                self._search_kg_by_text(query, at_time=at_time),
                self._search_entities_by_name(query),
            ]
        )
        kg_facts = kg_facts or []
        entities = entities or []
        fused = self._rrf_fuse(ftx_events or [], temporal_events or [])[:10]

        return {
            "strategy": "hybrid_bm25_vector_temporal",
            "events": _clean_output(fused[:10]),
            "entities": _clean_output(entities),
            "facts": _clean_output(kg_facts),
            "query": query,
            "retrieval_diagnostics": _channel_diagnostics(ftx_events or [], []),
        }

    async def _execute_semantic_hybrid(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute semantic hybrid — combines KG facts + vector events + FTX events + entity expansion."""
        budget_tracker.increment_tokens(len(query) // 3)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        ftx_events, vec_events, kg_facts, entities = await self._gather_bounded(
            [
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_events_vector(query, 10, since=since, until=until),
                self._search_kg_by_text(query, at_time=at_time),
                self._search_entities_by_name(query),
            ]
        )
        ftx_events = ftx_events or []
        vec_events = vec_events or []
        kg_facts = kg_facts or []
        entities = entities or []

        k = RRF_K
        seen_ids = set()
        fused = []
        for rank, ev in enumerate(ftx_events):
            eid = ev.get("id")
            if eid and eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf"] = 1.0 / (k + rank)
                fused.append(ev)
        for rank, ev in enumerate(vec_events):
            eid = ev.get("id")
            if not eid:
                continue
            if eid not in seen_ids:
                seen_ids.add(eid)
                # Rank contribution only. The previous version added
                # 0.5 * vec_score to the RRF term, but the two live on
                # incompatible scales: the RRF term spans 0.0132-0.0167 while
                # vec_score spans roughly 0.23-0.76, so the "0.5/0.5 blend"
                # measured at 2.1% RRF and 97.9% vector. The lexical channel
                # contributed nothing while appearing to. Adding an unbounded
                # and a bounded score with equal weights is not sound;
                # rank-based fusion is scale-free by construction.
                ev["_rrf"] = 1.0 / (k + len(ftx_events) + rank)
                fused.append(ev)
            else:
                for x in fused:
                    if x.get("id") == eid:
                        # Appears in both channels: both contribute a rank term,
                        # which is how RRF rewards agreement.
                        x["_rrf"] = x.get("_rrf", 0) + 1.0 / (k + len(ftx_events) + rank)
                        break
        fused.sort(key=lambda x: x.get("_rrf", 0), reverse=True)
        fused_events = fused[:10]
        for ev in fused_events:
            ev["relevance_score"] = round(ev.pop("_rrf", 0), 4)

        seen_entity_ids = {e.get("id") for e in entities if e.get("id")}
        expanded_entities = list(entities)
        seen_fact_ids = {f.get("id") for f in kg_facts if f.get("id")}
        expanded_facts = list(kg_facts)

        # Candidate names: capitalized query words first, then proper nouns from
        # the matched events. Bounded so the expansion cannot blow the budget.
        candidates = []
        for w in query.split():
            w_clean = w.strip(",.!?;:")
            if w_clean and not w_clean[0].islower() and len(w_clean) >= 2:
                candidates.append(w_clean)

        known_entity_names = {
            e.get("name", "").lower() for e in expanded_entities if e.get("name")
        }
        for ev in fused_events + ftx_events:
            for match in re.finditer(
                r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)\b", ev.get("content", "")
            ):
                name = match.group(1).strip()
                if len(name) >= 2 and name.lower() not in known_entity_names:
                    candidates.append(name)

        deduped = []
        seen_candidates = set()
        for name in candidates:
            key = name.lower()
            if key in seen_candidates or key in known_entity_names:
                continue
            seen_candidates.add(key)
            deduped.append(name)
        candidates = deduped[:MAX_EXPANSION_QUERIES]

        if candidates:
            entity_results = await self._gather_bounded(
                [self._search_entities_by_name(n) for n in candidates]
            )
            subject_names = list(candidates)
            for found in entity_results:
                for e in found or []:
                    eid = e.get("id")
                    if eid and eid not in seen_entity_ids:
                        seen_entity_ids.add(eid)
                        expanded_entities.append(e)
                        ename = e.get("name", "")
                        if ename and ename not in subject_names:
                            subject_names.append(ename)

            # The subject fan-out is bounded too: every candidate entity can
            # resolve to up to 20 further names, and an unbounded gather here
            # exhausted the DB budget and failed the whole query.
            # B2: bounded BFS to depth 2 instead of single-hop fan-out.
            bfs_facts = await self._expand_graph_bfs(
                subject_names[:MAX_EXPANSION_QUERIES],
                at_time=at_time,
                max_depth=2,
            )
            for f in bfs_facts:
                fid = f.get("id")
                if fid and fid not in seen_fact_ids:
                    seen_fact_ids.add(fid)
                    expanded_facts.append(f)

        return {
            "strategy": "semantic_hybrid",
            "events": _clean_output(fused_events),
            "entities": _clean_output(expanded_entities),
            "facts": _clean_output(expanded_facts),
            "query": query,
            "retrieval_diagnostics": _channel_diagnostics(ftx_events, vec_events),
        }

    async def _execute_hybrid_fallback(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute hybrid fallback strategy — search everything available including temporal fallback."""
        budget_tracker.increment_tokens(len(query) // 4)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        ftx_events, temporal_events, kg_facts, entities = await self._gather_bounded(
            [
                self._search_events_ftx(query, 5, since=since, until=until),
                self._search_recent_events(5, since=since, until=until),
                self._search_kg_by_text(query, at_time=at_time),
                self._search_entities_by_name(query),
            ]
        )
        kg_facts = kg_facts or []
        entities = entities or []
        fused = self._rrf_fuse(ftx_events or [], temporal_events or [])[:10]

        return {
            "strategy": "hybrid_fallback",
            "events": _clean_output(fused[:10]),
            "entities": _clean_output(entities),
            "facts": _clean_output(kg_facts),
            "query": query,
            "retrieval_diagnostics": _channel_diagnostics(ftx_events or [], []),
        }

    async def _execute_graph_ppr_rerank(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """PPR rerank (HippoRAG-lite): seed entities from the query, diffuse
        relevance over the 2-hop KG neighborhood, rank facts by endpoint mass.

        No hop-depth/direction tuning: association is a property of the
        diffusion, not of a traversal policy. Damping 0.5 keeps relevance
        query-local; seeds are IDF-penalized (weight / (1 + degree)) so hub
        entities don't dominate.
        """
        budget_tracker.increment_tokens(len(query) // 3)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        seeds = await self._seed_entity_names(query)
        if not seeds:
            # No linkable seeds: degrade to lexical+recent like event_log_first.
            ftx_events, temporal_events = await self._gather_bounded(
                [
                    self._search_events_ftx(query, 10, since=since, until=until),
                    self._search_recent_events(5, since=since, until=until),
                ]
            )
            fused = self._rrf_fuse(ftx_events or [], temporal_events or [])[:10]
            return {
                "strategy": "graph_ppr_rerank",
                "events": _clean_output(fused),
                "entities": [],
                "facts": [],
                "query": query,
                "ppr_fallback": "no_seeds",
            }

        # 2-hop subgraph around seeds (bounded fan-out, budget-tolerant).
        adjacency: Dict[str, Dict[str, float]] = {}
        fact_index: Dict[str, Dict] = {}

        async def _expand(names: List[str]) -> List[str]:
            results = await self._gather_bounded(
                [self._search_kg_by_subject(n, at_time=at_time) for n in names]
            )
            frontier: List[str] = []
            for more_facts in results:
                for f in more_facts or []:
                    fid = f.get("id")
                    a, b = f.get("in_id"), f.get("out_id")
                    if not a or not b:
                        continue
                    w = max(0.05, float(f.get("confidence") or 0.5))
                    adjacency.setdefault(a, {}).setdefault(b, 0.0)
                    adjacency[a][b] = max(adjacency[a][b], w)
                    adjacency.setdefault(b, {}).setdefault(a, 0.0)
                    adjacency[b][a] = max(adjacency[b][a], w)
                    if fid and fid not in fact_index:
                        fact_index[fid] = f
                    for nb in (a, b):
                        if nb not in frontier:
                            frontier.append(nb)
            return frontier

        level1 = await _expand(seeds[:MAX_EXPANSION_QUERIES])
        if len(adjacency) < PPR_MAX_NODES:
            await _expand(level1[: MAX_EXPANSION_QUERIES * 2])

        if not adjacency:
            return {
                "strategy": "graph_ppr_rerank",
                "events": [],
                "entities": [],
                "facts": [],
                "query": query,
                "ppr_fallback": "empty_graph",
            }

        # Seed masses: resolved seed entities get IDF-penalized weight.
        name_to_id: Dict[str, str] = {}
        ent_rows = await self._gather_bounded(
            [self._search_entities_by_name(s) for s in seeds[:MAX_EXPANSION_QUERIES]]
        )
        for found in ent_rows:
            for e in found or []:
                if e.get("name") and e.get("id"):
                    name_to_id[e["name"].lower()] = e["id"]
        personalization: Dict[str, float] = {}
        for s in seeds:
            eid = name_to_id.get(s.lower())
            if eid and eid in adjacency:
                degree = len(adjacency[eid])
                personalization[eid] = 1.0 / (1.0 + degree)
        if not personalization:
            # Seeds named entities that resolve to nothing: fall back to the
            # strongest graph hubs is wrong; degrade to lexical instead.
            ftx_events = await self._search_events_ftx(query, 10, since=since, until=until) or []
            return {
                "strategy": "graph_ppr_rerank",
                "events": _clean_output(ftx_events[:10]),
                "entities": [],
                "facts": [],
                "query": query,
                "ppr_fallback": "seeds_unresolved",
            }

        scores = personalized_pagerank(adjacency, personalization)

        ranked_facts = sorted(
            fact_index.values(),
            key=lambda f: max(
                scores.get(f.get("in_id", ""), 0.0),
                scores.get(f.get("out_id", ""), 0.0),
            ),
            reverse=True,
        )[:50]
        for f in ranked_facts:
            f["ppr_score"] = round(
                max(
                    scores.get(f.get("in_id", ""), 0.0),
                    scores.get(f.get("out_id", ""), 0.0),
                ),
                4,
            )
        ranked_entities = sorted(
            ({"id": nid, "name": "", "ppr_score": round(sc, 4)} for nid, sc in scores.items()),
            key=lambda e: e["ppr_score"],
            reverse=True,
        )[:20]

        ftx_events, temporal_events = await self._gather_bounded(
            [
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_recent_events(5, since=since, until=until),
            ]
        )
        fused = self._rrf_fuse(ftx_events or [], temporal_events or [])[:10]

        return {
            "strategy": "graph_ppr_rerank",
            "events": _clean_output(fused),
            "entities": _clean_output(ranked_entities),
            "facts": _clean_output(ranked_facts),
            "query": query,
        }

    async def _seed_entity_names(self, query: str) -> List[str]:
        """Candidate entity names from a query: capitalized words first, then
        proper nouns mined from top lexical hits (bounded)."""
        candidates: List[str] = []
        for w in query.split():
            w_clean = w.strip(",.!?;:")
            if w_clean and not w_clean[0].islower() and len(w_clean) >= 2:
                candidates.append(w_clean)
        try:
            ftx = await self._search_events_ftx(query, 5) or []
        except BudgetExceeded:
            ftx = []
        for ev in ftx:
            for match in re.finditer(
                r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)\b", ev.get("content", "")
            ):
                name = match.group(1).strip()
                if len(name) >= 2:
                    candidates.append(name)
        deduped, seen = [], set()
        for name in candidates:
            key = name.lower()
            if key not in seen:
                seen.add(key)
                deduped.append(name)
        return deduped[:MAX_EXPANSION_QUERIES]

    async def _execute_decomposed_multihop(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Split coordinated multi-hop queries into sub-queries (no LLM),
        retrieve per part (lexical + KG text), RRF-fuse across parts.

        Falls back to a single part (= plain hybrid) when no coordination is
        found, so this strategy is safe as a general multi-hop default.
        """
        budget_tracker.increment_tokens(len(query) // 3)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        parts = split_multihop_query(query)

        searches = []
        for part in parts[:MAX_EXPANSION_QUERIES]:
            searches.append(self._search_events_ftx(part, 10, since=since, until=until))
            searches.append(self._search_kg_by_text(part, at_time=at_time))
        all_results = await self._gather_bounded(searches)

        event_lists, fact_lists = [], []
        for i, r in enumerate(all_results):
            (event_lists if i % 2 == 0 else fact_lists).append(r or [])
        fused_events = self._rrf_fuse(*event_lists)[:10] if event_lists else []

        seen_fids, facts = set(), []
        for fl in fact_lists:
            for f in fl:
                fid = f.get("id")
                if fid and fid not in seen_fids:
                    seen_fids.add(fid)
                    facts.append(f)

        entities: List[Dict] = []
        seen_eids = set()
        ent_rows = await self._gather_bounded(
            [self._search_entities_by_name(p) for p in parts[:MAX_EXPANSION_QUERIES]]
        )
        for found in ent_rows:
            for e in found or []:
                eid = e.get("id")
                if eid and eid not in seen_eids:
                    seen_eids.add(eid)
                    entities.append(e)

        return {
            "strategy": "decomposed_multihop",
            "events": _clean_output(fused_events),
            "entities": _clean_output(entities),
            "facts": _clean_output(facts),
            "query": query,
            "sub_queries": parts,
        }


class PlanExecutor:
    """Executes complete plans using the retrieval executor"""

    def __init__(self):
        self.retrieval_executor = RetrievalExecutor()

    async def execute_plan(
        self, strategy: str, query: str, budget_level: str, **kwargs
    ) -> Dict[str, Any]:
        """
        Execute a complete plan with cost tracking and budget enforcement.
        """
        # Convert string to enum
        strategy_fallback = False
        try:
            strategy_enum = RetrievalStrategy(strategy)
        except ValueError:
            logging.warning("Unknown strategy '%s', falling back to hybrid_fallback", strategy)
            strategy_enum = RetrievalStrategy.HYBRID_FALLBACK
            strategy_fallback = True

        budget_fallback = False
        try:
            budget_enum = BudgetLevel(budget_level)
        except ValueError:
            logging.warning("Unknown budget level '%s', falling back to medium", budget_level)
            budget_enum = BudgetLevel.MEDIUM
            budget_fallback = True

        # Create budget tracker
        budget_tracker = BudgetTracker(budget_enum)

        # Execute the strategy
        result = await self.retrieval_executor.execute_strategy(
            strategy_enum, query, budget_tracker, **kwargs
        )

        # Add execution metadata. The effective values are reported, not the
        # requested ones: the requested strategy may have been replaced by a
        # fallback, and reporting the request made every fallback invisible.
        result["execution_metadata"] = {
            "requested_strategy": strategy,
            "strategy": strategy_enum.value,
            "requested_budget_level": budget_level,
            "budget_level": budget_enum.value,
            "fallback_applied": strategy_fallback or budget_fallback,
            "final_db_calls": budget_tracker.db_calls,
            "final_tokens": budget_tracker.estimated_tokens,
            "over_budget": budget_tracker.is_over_budget(),
        }

        return result


# For backward compatibility
async def execute_retrieval_strategy(
    strategy: str, query: str, **kwargs
) -> Dict[str, Any]:
    """Legacy function for executing retrieval strategies."""
    executor = PlanExecutor()
    return await executor.execute_plan(strategy, query, "medium", **kwargs)
