"""
Execution engine for the sieveon Memory Control Plane
Executes the plans generated by the planner using various retrieval strategies
"""

import asyncio
import contextvars
import logging
import os
import re
import sys
import time
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from ..extraction.entropy_gate import escape_surrealql
from ..mcp.core import _clean_output, _extract_result, _query_surreal
from ..router.cost_awareness import cost_tracker
from ..router.budget import BudgetLevel, BudgetTracker


class BudgetExceeded(Exception):
    """Raised when a strategy tries to exceed its allocated DB budget."""


RRF_K = 60
MAX_EXPANSION_QUERIES = 5

# A logically invalidated fact is only current while its validity window is open.
# Every read path in tools.py / core.py already applies this filter; the retrieval
# strategies did not, so a superseded value was still served as a current fact and
# memory_update's contract was void for 7 of the 8 strategies.
ACTIVE_FACT_FILTER = "(valid_until IS NONE OR valid_until > time::now())"


def _parse_ts(value: Any) -> Optional[datetime]:
    """Parse a SurrealDB datetime into an aware datetime, or None if unparsable."""
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=timezone.utc)
    if not isinstance(value, str):
        return None
    text = value.strip().replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)


class RetrievalStrategy(Enum):
    """Available retrieval strategies"""

    EVENT_LOG_FIRST = "event_log_first"
    KNOWLEDGE_GRAPH_FIRST = "knowledge_graph_first"
    HYBRID_WITH_GRAPH_EXPANSION = "hybrid_with_graph_expansion"
    COMPOSITE_KG_VECTOR = "composite_kg_vector"
    KNOWLEDGE_GRAPH_WITH_INVALIDATION = "knowledge_graph_with_invalidation"
    HYBRID_BM25_VECTOR_TEMPORAL = "hybrid_bm25_vector_temporal"
    HYBRID_FALLBACK = "hybrid_fallback"
    SEMANTIC_HYBRID = "semantic_hybrid"


class RetrievalExecutor:
    """Executes retrieval operations using different strategies"""

    def __init__(self):
        # ContextVar instead of a plain attribute: concurrent tasks sharing one
        # executor must not see each other's budget tracker.
        self._budget: contextvars.ContextVar = contextvars.ContextVar(
            "sieveon_budget_tracker", default=None
        )

    def _charge_db(self, count: int = 1):
        """Charge DB calls against the active budget and enforce the limit."""
        budget = self._budget.get()
        if budget is None:
            return
        if budget.is_over_budget():
            raise BudgetExceeded("Over budget")
        budget.increment_db_calls(count)

    async def _gather_bounded(self, coros: List[Any]) -> List[Any]:
        """Run searches concurrently, tolerating budget exhaustion.

        A BudgetExceeded inside asyncio.gather() cancels the sibling tasks and
        propagates, which turned "ran out of budget mid-expansion" into a total
        query failure. Expansion is an optional enrichment step, so a partial
        result set is the correct outcome: the cheapest searches (which are
        ordered first) survive and the rest come back as None.
        """
        if not coros:
            return []

        async def _guarded(coro):
            try:
                return await coro
            except BudgetExceeded:
                return None

        return await asyncio.gather(*(_guarded(c) for c in coros))

    @staticmethod
    def _rrf_fuse(*ranked_lists: List[Dict]) -> List[Dict]:
        """Reciprocal Rank Fusion over one or more ranked result lists."""
        seen_ids = set()
        fused: List[Dict] = []
        offset = 0
        for ranked in ranked_lists:
            for rank, item in enumerate(ranked):
                item_id = item.get("id")
                if not item_id or item_id in seen_ids:
                    continue
                seen_ids.add(item_id)
                item["_rrf_score"] = 1.0 / (RRF_K + offset + rank)
                fused.append(item)
            offset += len(ranked)

        fused.sort(key=lambda x: x.get("_rrf_score", 0.0), reverse=True)
        for item in fused:
            item["relevance_score"] = round(item.pop("_rrf_score", 0.0), 4)
        return fused

    async def execute_strategy(
        self,
        strategy: RetrievalStrategy,
        query: str,
        budget_tracker: BudgetTracker,
        **kwargs,
    ) -> Dict[str, Any]:
        """
        Execute a retrieval strategy with budget enforcement and cost tracking.
        """
        start_time = time.time()
        success = True
        relevance_score = 0.5
        budget_token = self._budget.set(budget_tracker)
        start_db_calls = budget_tracker.db_calls

        try:
            if budget_tracker.is_over_budget():
                raise BudgetExceeded("Over budget")

            if strategy == RetrievalStrategy.EVENT_LOG_FIRST:
                result = await self._execute_event_log_first(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.KNOWLEDGE_GRAPH_FIRST:
                result = await self._execute_knowledge_graph_first(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.HYBRID_WITH_GRAPH_EXPANSION:
                result = await self._execute_hybrid_with_graph_expansion(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.COMPOSITE_KG_VECTOR:
                result = await self._execute_composite_kg_vector(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.KNOWLEDGE_GRAPH_WITH_INVALIDATION:
                result = await self._execute_knowledge_graph_with_invalidation(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.HYBRID_BM25_VECTOR_TEMPORAL:
                result = await self._execute_hybrid_bm25_vector_temporal(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.HYBRID_FALLBACK:
                result = await self._execute_hybrid_fallback(
                    query, budget_tracker, **kwargs
                )
            elif strategy == RetrievalStrategy.SEMANTIC_HYBRID:
                result = await self._execute_semantic_hybrid(
                    query, budget_tracker, **kwargs
                )
            else:
                raise ValueError(f"Unknown strategy: {strategy}")

            relevance_score = self._calculate_relevance_score(result, query)

        except Exception as e:
            success = False
            logging.error("Strategy %s failed: %s", strategy.value, e, exc_info=True)
            result = {
                "error": str(e),
                "error_type": type(e).__name__,
                "success": False,
                "strategy": strategy.value,
                "events": [],
                "entities": [],
                "facts": [],
                "query": query,
            }
        finally:
            self._budget.reset(budget_token)
            latency = time.time() - start_time
            num_queries = budget_tracker.db_calls - start_db_calls

            cost_tracker.record_request(
                strategy=strategy.value,
                latency=latency,
                success=success,
                num_queries=num_queries,
                relevance=relevance_score,
            )

        # Surfaced so callers can see the score that was fed into the router's
        # cost tracking instead of having to reconstruct it.
        result["relevance_score"] = relevance_score

        return result

    _TERM_RE = re.compile(r"\w{3,}")

    @classmethod
    def _item_text(cls, item: Dict[str, Any]) -> str:
        """Flatten the searchable text of a result item (event/entity/fact)."""
        parts: List[Any] = [
            item.get("content"),
            item.get("name"),
            item.get("predicate"),
            item.get("in_name"),
            item.get("out_name"),
        ]
        for edge in ("in", "out"):
            value = item.get(edge)
            if isinstance(value, dict):
                parts.append(value.get("name"))
                parts.append(value.get("type"))
            elif isinstance(value, str):
                parts.append(value)
        return " ".join(str(p) for p in parts if p).lower()

    @classmethod
    def _calculate_relevance_score(cls, result: Dict[str, Any], query: str) -> float:
        """Calculate a relevance score based on the result quality.

        Volume alone is not relevance: returning 50 unrelated rows scored higher
        than returning 3 exact matches, and that score feeds cost_tracker, which
        made the router prefer high-volume strategies regardless of quality.
        The score now weights coverage (share of items containing a query term)
        first and uses result volume only as a secondary signal.
        """
        if "error" in result:
            return 0.1

        items: List[Dict[str, Any]] = []
        for key in ("events", "entities", "facts"):
            value = result.get(key, [])
            if isinstance(value, list):
                items.extend(i for i in value if isinstance(i, dict))

        total = len(items)
        if total == 0:
            return 0.2

        terms = set(cls._TERM_RE.findall(query.lower()))
        if terms:
            matched = sum(
                1 for item in items if terms & set(cls._TERM_RE.findall(cls._item_text(item)))
            )
            coverage = matched / total
        else:
            coverage = 0.0

        volume = min(1.0, total / 10.0)
        return round(min(1.0, 0.2 + 0.6 * coverage + 0.2 * volume), 4)


    @staticmethod
    def _temporal_clause(since: Optional[str] = None, until: Optional[str] = None) -> str:
        """SQL fragment restricting event timestamps (B1 temporal path).

        Uses fn::events_at semantics inline so the FTX/vector channels stay
        index-friendly. Values are SurrealQL-escaped ISO datetimes.
        """
        clauses = []
        if since:
            clauses.append(f'AND timestamp >= type::datetime("{escape_surrealql(since)}")')
        if until:
            clauses.append(f'AND timestamp <= type::datetime("{escape_surrealql(until)}")')
        return "\n          ".join(clauses)

    @staticmethod
    def _validity_at_clause(at_time: Optional[str] = None) -> str:
        """Validity window at a fixed point in time (B1: 'was wusste der Agent zu T').

        None -> current validity (valid_until IS NONE OR > now()).
        Set -> valid_from <= T AND (valid_until NONE OR > T), same rule as
        fn::facts_at_time($time) in docs/helper_functions.surql.
        """
        if not at_time:
            return f"AND {ACTIVE_FACT_FILTER}"
        t = escape_surrealql(at_time)
        return f'AND valid_from <= type::datetime("{t}") AND (valid_until IS NONE OR valid_until > type::datetime("{t}"))'

    async def _search_events_ftx(
        self,
        query: str,
        limit: int = 10,
        since: Optional[str] = None,
        until: Optional[str] = None,
    ) -> List[Dict]:
        """Lexical search via FTX index."""
        self._charge_db()
        query_escaped = escape_surrealql(query)
        forgotten_filter = "forgotten = false"
        temporal = self._temporal_clause(since, until)
        sql = f"""
        SELECT id, content, timestamp, source, metadata
        FROM event
        WHERE content @@ '{query_escaped}'
          AND {forgotten_filter}
          {temporal}
        LIMIT {limit * 4};
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_events_vector(
        self,
        query: str,
        limit: int = 10,
        since: Optional[str] = None,
        until: Optional[str] = None,
    ) -> List[Dict]:
        """Semantic search via vector similarity."""
        from src.mcp.core import _embed_query

        query_vector = await _embed_query(query)
        if not query_vector:
            return []
        self._charge_db()
        query_vector_str = "[" + ", ".join(map(str, query_vector)) + "]"
        forgotten_filter = "forgotten = false"
        temporal = self._temporal_clause(since, until)
        sql = f"""
        SELECT id, content, timestamp, source, metadata,
               vector::similarity::cosine(embedding, {query_vector_str}) AS vec_score
        FROM event
        WHERE embedding IS NOT NONE
          AND {forgotten_filter}
          {temporal}
          AND array::len(embedding) = {len(query_vector)}
        ORDER BY vec_score DESC
        LIMIT {limit * 4};
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_recent_events(
        self,
        limit: int = 10,
        since: Optional[str] = None,
        until: Optional[str] = None,
    ) -> List[Dict]:
        """Recency channel: the most recent events, regardless of the query.

        Deliberately not query-conditioned. It is fused with the lexical results
        via RRF to bias towards fresh events; adding a query filter here would
        only turn it into a subset of the FTX results and double-count them.
        since/until bound the window (B1: fn::events_at semantics).
        """
        self._charge_db()
        forgotten_filter = "forgotten = false"
        temporal = self._temporal_clause(since, until)
        sql = f"""
        SELECT id, content, timestamp, source, metadata
        FROM event
        WHERE {forgotten_filter}
          {temporal}
        ORDER BY timestamp DESC
        LIMIT {limit};
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    @staticmethod
    def _validity_clause(include_invalidated: bool) -> str:
        """SQL clause restricting facts to an open validity window."""
        return "" if include_invalidated else f"AND {ACTIVE_FACT_FILTER}"

    async def _search_kg_by_subject(
        self,
        subject: str,
        include_invalidated: bool = False,
        at_time: Optional[str] = None,
    ) -> List[Dict]:
        """Search knowledge graph by subject name.

        Only currently valid facts unless include_invalidated is set; that flag
        exists for the strategy that reports the validity split explicitly.
        at_time pins the validity window (B1, fn::facts_at_time semantics).
        """
        self._charge_db()
        subject_escaped = escape_surrealql(subject)
        validity = (
            ""
            if include_invalidated and not at_time
            else self._validity_at_clause(at_time)
        )
        sql = f"""
        SELECT id,
               in.name AS in_name, in.type AS in_type, in.id AS in_id,
               out.name AS out_name, out.type AS out_type, out.id AS out_id,
               predicate, confidence, valid_from, valid_until
        FROM fact
        WHERE in.name = '{subject_escaped}'
          {validity}
        ORDER BY confidence DESC
        LIMIT 50;
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_kg_by_text(
        self,
        text: str,
        include_invalidated: bool = False,
        at_time: Optional[str] = None,
    ) -> List[Dict]:
        """Search knowledge graph by matching predicate or entity names.

        The OR group is parenthesised so the validity filter applies to all three
        branches instead of binding to the last one only.
        """
        self._charge_db()
        text_escaped = escape_surrealql(text)
        validity = (
            ""
            if include_invalidated and not at_time
            else self._validity_at_clause(at_time)
        )
        sql = f"""
        SELECT id,
               in.name AS in_name, in.type AS in_type, in.id AS in_id,
               out.name AS out_name, out.type AS out_type, out.id AS out_id,
               predicate, confidence, valid_from, valid_until
        FROM fact
        WHERE (predicate @@ '{text_escaped}'
            OR in.name CONTAINS '{text_escaped}'
            OR out.name CONTAINS '{text_escaped}')
          {validity}
        ORDER BY confidence DESC
        LIMIT 50;
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _search_entities_by_name(self, name: str) -> List[Dict]:
        """Search entities by name (fulltext via FTX index)."""
        self._charge_db()
        name_escaped = escape_surrealql(name)
        sql = f"""
        SELECT id, name, type
        FROM entity
        WHERE name @@ '{name_escaped}'
        LIMIT 20;
        """
        result = await _query_surreal(sql)
        return _extract_result(result, 1) or []

    async def _expand_graph_bfs(
        self,
        seed_names: List[str],
        at_time: Optional[str] = None,
        max_depth: int = 2,
        per_level: int = MAX_EXPANSION_QUERIES,
    ) -> List[Dict]:
        """Bounded BFS graph expansion (B2).

        Level 0 = seed entity names. Each level queries _search_kg_by_subject
        for up to `per_level` names, collects neighbour names for the next
        level. Budget-exhaustion returns partial results via _gather_bounded.
        Respects at_time validity windows.
        """
        seen_fact_ids: set = set()
        expanded: List[Dict] = []
        frontier = [n for n in dict.fromkeys(seed_names) if n][:per_level]
        seen_names = set(frontier)
        for _ in range(max(1, max_depth)):
            if not frontier:
                break
            level_results = await self._gather_bounded(
                [self._search_kg_by_subject(n, at_time=at_time) for n in frontier[:per_level]]
            )
            next_frontier: List[str] = []
            for more_facts in level_results:
                for f in more_facts or []:
                    fid = f.get("id")
                    if fid and fid not in seen_fact_ids:
                        seen_fact_ids.add(fid)
                        expanded.append(f)
                    for key in ("in_name", "out_name"):
                        neighbour = f.get(key)
                        if neighbour and neighbour not in seen_names:
                            seen_names.add(neighbour)
                            next_frontier.append(neighbour)
            frontier = next_frontier[:per_level]
        return expanded

    async def _execute_event_log_first(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute event log first strategy — search events via FTX + temporal."""
        budget_tracker.increment_tokens(len(query) // 4)
        since = kwargs.get("since")
        until = kwargs.get("until")

        ftx_events, temporal_events = await self._gather_bounded(
            [
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_recent_events(5, since=since, until=until),
            ]
        )
        ftx_events = ftx_events or []
        temporal_events = temporal_events or []

        fused = self._rrf_fuse(ftx_events, temporal_events)[:10]

        return {
            "strategy": "event_log_first",
            "events": _clean_output(fused[:10]),
            "entities": [],
            "facts": [],
            "query": query,
        }

    async def _execute_knowledge_graph_first(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute knowledge graph first strategy — search KG + entities."""
        budget_tracker.increment_tokens(len(query) // 4)
        at_time = kwargs.get("at_time")

        # Extract potential subject words from query (simple heuristic)
        words = query.split()
        subjects_to_try = []
        for w in words:
            w_clean = w.strip(",.!?;:")
            if w_clean and w_clean[0].isupper():
                subjects_to_try.append(w_clean)
        if not subjects_to_try:
            subjects_to_try = [query]

        # Search entities and KG in parallel
        searches = [self._search_entities_by_name(s) for s in subjects_to_try[:3]]
        searches.append(self._search_kg_by_text(query, at_time=at_time))

        all_results = await self._gather_bounded(searches)

        entities = []
        seen_entity_ids = set()
        for r in all_results[: len(searches) - 1]:
            for e in r or []:
                eid = e.get("id")
                if eid and eid not in seen_entity_ids:
                    seen_entity_ids.add(eid)
                    entities.append(e)

        facts = []
        seen_fact_ids = set()
        for r in all_results[len(searches) - 1 :]:
            for f in r or []:
                fid = f.get("id")
                if fid and fid not in seen_fact_ids:
                    seen_fact_ids.add(fid)
                    facts.append(f)

        return {
            "strategy": "knowledge_graph_first",
            "events": [],
            "entities": _clean_output(entities),
            "facts": _clean_output(facts),
            "query": query,
        }

    async def _execute_hybrid_with_graph_expansion(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute hybrid with graph expansion — events + KG + BFS entity expansion."""
        budget_tracker.increment_tokens(len(query) // 3)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        ftx_events, kg_facts, entities = await self._gather_bounded(
            [
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_kg_by_text(query, at_time=at_time),
                self._search_entities_by_name(query),
            ]
        )
        ftx_events = ftx_events or []
        kg_facts = kg_facts or []
        entities = entities or []

        # Expand via bounded BFS (B2): seeds -> neighbours -> neighbours-of-neighbours
        expanded_facts = list(kg_facts)
        seen_fact_ids = {f.get("id") for f in kg_facts if f.get("id")}
        subject_names = []
        for ent in entities[:MAX_EXPANSION_QUERIES]:
            ent_name = ent.get("name", "")
            if ent_name and ent_name not in subject_names:
                subject_names.append(ent_name)

        if subject_names:
            bfs_facts = await self._expand_graph_bfs(
                subject_names, at_time=at_time, max_depth=2
            )
            for f in bfs_facts:
                fid = f.get("id")
                if fid and fid not in seen_fact_ids:
                    seen_fact_ids.add(fid)
                    expanded_facts.append(f)

        return {
            "strategy": "hybrid_with_graph_expansion",
            "events": _clean_output(ftx_events),
            "entities": _clean_output(entities),
            "facts": _clean_output(expanded_facts),
            "query": query,
        }

    async def _execute_composite_kg_vector(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute composite KG-vector strategy — KG facts + lexical and vector search on events."""
        budget_tracker.increment_tokens(len(query) // 3)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        kg_facts, entities, ftx_events, vec_events = await self._gather_bounded(
            [
                self._search_kg_by_text(query, at_time=at_time),
                self._search_entities_by_name(query),
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_events_vector(query, 10, since=since, until=until),
            ]
        )
        kg_facts = kg_facts or []
        entities = entities or []
        fused = self._rrf_fuse(ftx_events or [], vec_events or [])[:10]

        return {
            "strategy": "composite_kg_vector",
            "events": _clean_output(fused),
            "entities": _clean_output(entities),
            "facts": _clean_output(kg_facts),
            "query": query,
        }

    async def _execute_knowledge_graph_with_invalidation(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute knowledge graph with invalidation — search KG + check for stale facts.

        This is the one strategy that needs the invalidated rows: it reports the
        validity split (active / stale / expired) instead of dropping them.
        """
        budget_tracker.increment_tokens(len(query) // 4)

        kg_facts, entities = await self._gather_bounded(
            [
                self._search_kg_by_text(
                    query,
                    include_invalidated=True,
                    at_time=kwargs.get("at_time"),
                ),
                self._search_entities_by_name(query),
            ]
        )
        kg_facts = kg_facts or []
        entities = entities or []

        # Read-side invalidation only: no writes, facts are split by validity window.
        #
        # "Current" follows ACTIVE_FACT_FILTER, so a fact with a scheduled future end
        # date is still current — the same rule every other read path in the codebase
        # applies. Buckets:
        #   facts         valid_until empty or in the future  -> currently true
        #   expired_facts valid_until in the past            -> superseded
        #   stale_facts   valid_until present but unparsable -> data quality, cannot
        #                 be placed in time; kept in the current set so it is not
        #                 silently dropped, and counted below so it can be alerted on
        now = datetime.now(timezone.utc)
        active_facts = []
        stale_facts = []
        expired_facts = []
        unparsable = 0
        for fact in kg_facts:
            valid_until = fact.get("valid_until")
            if not valid_until:
                active_facts.append(fact)
                continue

            deadline = _parse_ts(valid_until)
            if deadline is None:
                unparsable += 1
                stale_facts.append(fact)
                active_facts.append(fact)
            elif deadline <= now:
                expired_facts.append(fact)
            else:
                active_facts.append(fact)

        if unparsable:
            logging.warning(
                "%d fact(s) carry an unparsable valid_until and could not be placed "
                "in a validity window",
                unparsable,
            )

        return {
            "strategy": "knowledge_graph_with_invalidation",
            "events": [],
            "entities": _clean_output(entities),
            "facts": _clean_output(active_facts),
            "stale_facts": _clean_output(stale_facts),
            "expired_facts": _clean_output(expired_facts),
            "unparsable_valid_until": unparsable,
            "query": query,
        }

    async def _execute_hybrid_bm25_vector_temporal(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute hybrid BM25-vector-temporal — full event search + KG."""
        budget_tracker.increment_tokens(len(query) // 3)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        ftx_events, temporal_events, kg_facts, entities = await self._gather_bounded(
            [
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_recent_events(5, since=since, until=until),
                self._search_kg_by_text(query, at_time=at_time),
                self._search_entities_by_name(query),
            ]
        )
        kg_facts = kg_facts or []
        entities = entities or []
        fused = self._rrf_fuse(ftx_events or [], temporal_events or [])[:10]

        return {
            "strategy": "hybrid_bm25_vector_temporal",
            "events": _clean_output(fused[:10]),
            "entities": _clean_output(entities),
            "facts": _clean_output(kg_facts),
            "query": query,
        }

    async def _execute_semantic_hybrid(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute semantic hybrid — combines KG facts + vector events + FTX events + entity expansion."""
        budget_tracker.increment_tokens(len(query) // 3)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        ftx_events, vec_events, kg_facts, entities = await self._gather_bounded(
            [
                self._search_events_ftx(query, 10, since=since, until=until),
                self._search_events_vector(query, 10, since=since, until=until),
                self._search_kg_by_text(query, at_time=at_time),
                self._search_entities_by_name(query),
            ]
        )
        ftx_events = ftx_events or []
        vec_events = vec_events or []
        kg_facts = kg_facts or []
        entities = entities or []

        k = RRF_K
        seen_ids = set()
        fused = []
        for rank, ev in enumerate(ftx_events):
            eid = ev.get("id")
            if eid and eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf"] = 1.0 / (k + rank)
                fused.append(ev)
        for rank, ev in enumerate(vec_events):
            vec_score = ev.get("vec_score", 0) or 0
            weighted = 0.5 * (1.0 / (k + len(ftx_events) + rank)) + 0.5 * vec_score
            eid = ev.get("id")
            if not eid:
                continue
            if eid not in seen_ids:
                seen_ids.add(eid)
                ev["_rrf"] = weighted
                fused.append(ev)
            else:
                for x in fused:
                    if x.get("id") == eid:
                        x["_rrf"] = x.get("_rrf", 0) + weighted
                        break
        fused.sort(key=lambda x: x.get("_rrf", 0), reverse=True)
        fused_events = fused[:10]
        for ev in fused_events:
            ev["relevance_score"] = round(ev.pop("_rrf", 0), 4)

        seen_entity_ids = {e.get("id") for e in entities if e.get("id")}
        expanded_entities = list(entities)
        seen_fact_ids = {f.get("id") for f in kg_facts if f.get("id")}
        expanded_facts = list(kg_facts)

        # Candidate names: capitalized query words first, then proper nouns from
        # the matched events. Bounded so the expansion cannot blow the budget.
        candidates = []
        for w in query.split():
            w_clean = w.strip(",.!?;:")
            if w_clean and not w_clean[0].islower() and len(w_clean) >= 2:
                candidates.append(w_clean)

        known_entity_names = {
            e.get("name", "").lower() for e in expanded_entities if e.get("name")
        }
        for ev in fused_events + ftx_events:
            for match in re.finditer(
                r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)\b", ev.get("content", "")
            ):
                name = match.group(1).strip()
                if len(name) >= 2 and name.lower() not in known_entity_names:
                    candidates.append(name)

        deduped = []
        seen_candidates = set()
        for name in candidates:
            key = name.lower()
            if key in seen_candidates or key in known_entity_names:
                continue
            seen_candidates.add(key)
            deduped.append(name)
        candidates = deduped[:MAX_EXPANSION_QUERIES]

        if candidates:
            entity_results = await self._gather_bounded(
                [self._search_entities_by_name(n) for n in candidates]
            )
            subject_names = list(candidates)
            for found in entity_results:
                for e in found or []:
                    eid = e.get("id")
                    if eid and eid not in seen_entity_ids:
                        seen_entity_ids.add(eid)
                        expanded_entities.append(e)
                        ename = e.get("name", "")
                        if ename and ename not in subject_names:
                            subject_names.append(ename)

            # The subject fan-out is bounded too: every candidate entity can
            # resolve to up to 20 further names, and an unbounded gather here
            # exhausted the DB budget and failed the whole query.
            # B2: bounded BFS to depth 2 instead of single-hop fan-out.
            bfs_facts = await self._expand_graph_bfs(
                subject_names[:MAX_EXPANSION_QUERIES],
                at_time=at_time,
                max_depth=2,
            )
            for f in bfs_facts:
                fid = f.get("id")
                if fid and fid not in seen_fact_ids:
                    seen_fact_ids.add(fid)
                    expanded_facts.append(f)

        return {
            "strategy": "semantic_hybrid",
            "events": _clean_output(fused_events),
            "entities": _clean_output(expanded_entities),
            "facts": _clean_output(expanded_facts),
            "query": query,
        }

    async def _execute_hybrid_fallback(
        self, query: str, budget_tracker: BudgetTracker, **kwargs
    ) -> Dict[str, Any]:
        """Execute hybrid fallback strategy — search everything available including temporal fallback."""
        budget_tracker.increment_tokens(len(query) // 4)
        since = kwargs.get("since")
        until = kwargs.get("until")
        at_time = kwargs.get("at_time")

        ftx_events, temporal_events, kg_facts, entities = await self._gather_bounded(
            [
                self._search_events_ftx(query, 5, since=since, until=until),
                self._search_recent_events(5, since=since, until=until),
                self._search_kg_by_text(query, at_time=at_time),
                self._search_entities_by_name(query),
            ]
        )
        kg_facts = kg_facts or []
        entities = entities or []
        fused = self._rrf_fuse(ftx_events or [], temporal_events or [])[:10]

        return {
            "strategy": "hybrid_fallback",
            "events": _clean_output(fused[:10]),
            "entities": _clean_output(entities),
            "facts": _clean_output(kg_facts),
            "query": query,
        }


class PlanExecutor:
    """Executes complete plans using the retrieval executor"""

    def __init__(self):
        self.retrieval_executor = RetrievalExecutor()

    async def execute_plan(
        self, strategy: str, query: str, budget_level: str, **kwargs
    ) -> Dict[str, Any]:
        """
        Execute a complete plan with cost tracking and budget enforcement.
        """
        # Convert string to enum
        strategy_fallback = False
        try:
            strategy_enum = RetrievalStrategy(strategy)
        except ValueError:
            logging.warning("Unknown strategy '%s', falling back to hybrid_fallback", strategy)
            strategy_enum = RetrievalStrategy.HYBRID_FALLBACK
            strategy_fallback = True

        budget_fallback = False
        try:
            budget_enum = BudgetLevel(budget_level)
        except ValueError:
            logging.warning("Unknown budget level '%s', falling back to medium", budget_level)
            budget_enum = BudgetLevel.MEDIUM
            budget_fallback = True

        # Create budget tracker
        budget_tracker = BudgetTracker(budget_enum)

        # Execute the strategy
        result = await self.retrieval_executor.execute_strategy(
            strategy_enum, query, budget_tracker, **kwargs
        )

        # Add execution metadata. The effective values are reported, not the
        # requested ones: the requested strategy may have been replaced by a
        # fallback, and reporting the request made every fallback invisible.
        result["execution_metadata"] = {
            "requested_strategy": strategy,
            "strategy": strategy_enum.value,
            "requested_budget_level": budget_level,
            "budget_level": budget_enum.value,
            "fallback_applied": strategy_fallback or budget_fallback,
            "final_db_calls": budget_tracker.db_calls,
            "final_tokens": budget_tracker.estimated_tokens,
            "over_budget": budget_tracker.is_over_budget(),
        }

        return result


# For backward compatibility
async def execute_retrieval_strategy(
    strategy: str, query: str, **kwargs
) -> Dict[str, Any]:
    """Legacy function for executing retrieval strategies."""
    executor = PlanExecutor()
    return await executor.execute_plan(strategy, query, "medium", **kwargs)
